### ISSUE TITLE
最终用户搜索问题

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#17]
最终用户不会被搜索到（需要更改） @chanchengliang @zxc37880

**Comment by winder1986** [comment]
麻煩說明是在哪個地方的搜索等(說明操作情境)

**Comment by zxc37880** [comment]
麻煩說明是在哪個地方的搜索等(說明操作情境)

**Comment by winder1986** [comment]
在所有客户列表（已成交客户的最终用户为：winder测试，在所有客户列表无法搜索到，但可以在已成交客户列表搜索到）

**Comment by zxc37880** [comment]
ok. 加入搜索最終客戶條件，雖前面表格看不到但可搜尋到相關的資料

**Comment by winder1986** [comment]
ok，
close
