### ISSUE TITLE
创建报价单/产品资料  数据是否正确？

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#22]
报价单功能只提供给直销人员使用，但是在产品资料里面有很多选项涉及经销商，比如：华康典藏基本版POSA（经销商）等

**Comment by zxc37880** [comment]
請在提供所需產品欄位，在修改為正確欄位。

**Comment by winder1986** [comment]
稍后会和业务人员联系，确认好目前的产品和价格后再和你沟通

**Comment by winder1986** [comment]
已通过邮件提供相应数据，close
