### ISSUE TITLE
数据库数据修改

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#25]
原先登记不规范（现在创建时自动校正为英文半角括号），很多带（）的公司名称，出现中文括号格式或中英混搭的情况，导致公司无法查询或者被重复登记的情况。  是否方便将数据库中“客户名称”和“最终用户”栏出现的括号全部更正为英文半角。

**Comment by zxc37880** [comment]
ok.已修正

**Comment by winder1986** [comment]
ok，close
