### ISSUE TITLE
侵权客户和潜在客户（已过期）重新创建后，原数据记录需删除

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#29]
侵权客户和潜在客户（已过期）重新创建后，原数据记录需删除
ps：已成交客户（已过期）60天后可以被重新创建，**但是原记录不删除**

**Comment by zxc37880** [comment]
若該資料庫裡有查詢到兩筆同樣名稱資料，將刪除最新一筆資料後，新增欲新增客戶資料。(此筆資料為下次判斷過期與否之標準)
已成交客戶不刪除，功能ok。

**Comment by winder1986** [comment]
可以。

**Comment by winder1986** [comment]
ok，close
