### ISSUE TITLE
上傳後，下載的excel的報表

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#37]
欄文中文混雜，欄寬未修正

**Comment by zxc37880** [comment]
已修正.

**Comment by chanchengliang** [comment]
起始時間為null，未可更新延期。
->應改為：起始時間為空值，無法更新延期。

**Comment by chanchengliang** [comment]
[3333.xlsx](https://github.com/chanchengliang/Dynacw_ChinaAgent/files/2556848/3333.xlsx)
既然無法更改，為何在即將到期的名單內？
