### ISSUE TITLE
同一份延期的客戶名單重複上傳

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#38]
重複上傳是可以被通過的(同意此情況)，但報表結果和第一次一樣？？

**Comment by zxc37880** [comment]
已修正. 
重複上傳應該是已經延期，因此可以通過上傳，但點選批次延期按鈕後才會比對SQL資料庫，出來的結果會顯示數字0、1、2、6代表是否成功。

已修正把上傳後報表下載只會有一個工作表匯出結果。

**Comment by chanchengliang** [comment]
當第一次客戶A名單上傳並且成功後。照理來說，A名單，就不會在"即將到期客戶列表中"了，第二次重複上傳時，比對應該會失敗。怎麼會再次延期成功？

**Comment by zxc37880** [comment]
ok. 比對表已從全部客戶改為即將到期名單
