### ISSUE TITLE
上傳客戶名單，檔名未檢查，檔案的內容是空的

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#42]
[null%_.xlsx](https://github.com/chanchengliang/Dynacw_ChinaAgent/files/2555823/null._.xlsx)
檔案是空的，還能跳出結果

**Comment by zxc37880** [comment]
功能來說
上傳只是將檔案上傳至伺服器，點選批次延期按鈕後才會進行SQL比對。
因此只需注意產出後下載的結果檔案中，他的結果是否為0以外的數字，就知道是否新增成功了。

**Comment by chanchengliang** [comment]
應該是先檢查檔案為空，就直接提示使用者檔案內容為空，請重新上傳，而不是丟出Exception的訊息給使用者。

**Comment by zxc37880** [comment]
已修正.
