### ISSUE TITLE
檢查客戶名稱

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#44]
雖然擋下了（　　(，但用「貼上」的方式還是能夠避開。

**Comment by chanchengliang** [comment]
查後端的資料庫客戶名稱，()的方式看來是有需求的，如附圖。
![1](https://user-images.githubusercontent.com/9152238/48179798-d206f300-e35b-11e8-95db-5973fe932395.jpg)

**Comment by zxc37880** [comment]
已修正.

**Comment by chanchengliang** [comment]
"郑州楼兰丝路电子商务有限公司 "為侵權客戶，在創建客戶時在客戶名稱輸入"郑州楼兰丝路电子商务(有限)公司", 會出現此客戶尚未登記的結果。

**Comment by zxc37880** [comment]
以更改搜尋方式，完成。
