### ISSUE TITLE
ID此兩字大小寫不一致

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#45]
下載的excel(即到到期客戶)，ID為全部大寫。
ID | 客户名称 | 潜在或侵权 | 匹配 | 延期条件 | 延期结果
-- | -- | -- | -- | -- | --

範本，和報表，為小寫。請統一，請連頁面的ID一併修改。

**Comment by zxc37880** [comment]
已修正

**Comment by chanchengliang** [comment]
頁面各頁的Id欄為"Id"，而下載「最近一個月的即將到期客戶報表」報表欄位為"ID"

**Comment by zxc37880** [comment]
ok.
