### ISSUE TITLE
系統若超過時間沒用時不會自動登出，會跳錯誤頁面

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#48]

**Comment by chanchengliang** [comment]
![2018-11-8 01-30-53](https://user-images.githubusercontent.com/9152238/48179535-a9cac480-e35a-11e8-846b-e85c46b64c51.jpg)

**Comment by zxc37880** [comment]
再試試看，應該修正了。

**Comment by chanchengliang** [comment]
![333](https://user-images.githubusercontent.com/9152238/48749069-2e4f0880-ecb4-11e8-8ede-637779e12566.jpg)

**Comment by zxc37880** [comment]
如果可以請貼上導向的錯誤網址來debug
