### ISSUE TITLE
各頁的Table的欄位，排序功能不work

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#49]

**Comment by zxc37880** [comment]
ok.

**Comment by chanchengliang** [comment]
![123](https://user-images.githubusercontent.com/9152238/48699545-ad94fb80-ec24-11e8-80a5-f16c9bb022bf.jpg)

所有客戶列表，按下「截止時間」欄位的標題欄後(order)，會出現invalidate time，應該「空白」就好了

**Comment by zxc37880** [comment]
ok.

**Comment by chanchengliang** [comment]
?

**Comment by zxc37880** [comment]
ok..
