### ISSUE TITLE
已成交客戶的第一頁最後一筆，會出現在第二頁的第一筆(重複出現)

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#53]
![22](https://user-images.githubusercontent.com/9152238/48748690-a7e5f700-ecb2-11e8-9818-895213758b24.jpg)
![333](https://user-images.githubusercontent.com/9152238/48748724-c6e48900-ecb2-11e8-9981-d7fbf0423760.jpg)

**Comment by chanchengliang** [comment]
其它頁面的也一樣有相同的問題

**Comment by zxc37880** [comment]
ok..
