### ISSUE TITLE
疑问：已成交客户重新创建提醒功能。

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#57]
已成交（已过期）客户，重新创建时，点击“检查客户名称”应 该提示客户最新一次成交记录的“截止日期”，目前正式站是这样的。但是在测试站没有该功能，更新后是否会影响正式站。

**Comment by zxc37880** [comment]
寫新的規則時沒有注意到這部分，已修改。
