### ISSUE TITLE
正式站，新增客户--客户名称输入框,输入“（）”后保存，保存结果“（）”会取消

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#59]
举例：新增客户名称：华康（北京）测试，保存后，名称变为：华康北京测试。其中的“（）”会自动取消

**Comment by zxc37880** [comment]
正式站與測試站都已修正此問題(在設計時把前端輸入的符號做限制，若輸入其他符號會自動replace為空白)。
