### ISSUE TITLE
以李永生帳號登入後修改下列客戶(侵權資料)，會報錯。

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#65]
http://testchinaagent.dfo.dynacw.com.cn//CustomersEx/Edit/22304

**Comment by winder1986** [comment]
添加“侵权证据”后，点击保存会报错。（原无侵权证据的客户，编辑，添加“侵权证据”后保存报错；如原侵权客户已存在侵权证据，编辑，再添加侵权证据后可以正常保存）

**Comment by zxc37880** [comment]
以修正此問題，請再確認是否有錯。

**Comment by winder1986** [comment]
已测试，ok！可以更新到正式站

**Comment by winder1986** [comment]
已测试完成，均已OK，可以更新到正式站，感谢！
