### ISSUE TITLE
將2018/5/31後創建的客戶的截止日期調整，即在創建日期的基礎上增加一年

### ISSUE THREAD

**Issue by chanchengliang** [chanchengliang/Dynacw_ChinaAgent#74]
將2018/5/31後創建的客戶的截止日期調整，即在創建日期的基礎上增加一年。

**Comment by zxc37880** [comment]
正式站DB以修改。

**Comment by winder1986** [comment]
ok，已验证，感谢！

**Comment by winder1986** [comment]
你好，该改动能够恢复原来数据吗？发现个比较严重的问题，2018/5/30后创建的已成交客户不能修改截止日期。

**Comment by winder1986** [comment]
或者提供一份客户名单，按照名单的截止日期进行恢复

**Comment by zxc37880** [comment]
目前恢復回當初尚未添加一年的資料了。

**Comment by winder1986** [comment]
ok，已测试恢复完成。然后针对侵权和潜在客户，仍需要进行截止日期调整，截止日期=创建日期+1年。已成交客户不需要调整日期。感谢！
