### ISSUE TITLE
已成交客户（已过期）无法再次创建       （请尽快 处理）

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#75]
已成交客户（已过期），再次创建时，点击“检查客户名称”，提示可以创建，但是点击“创建客户”按钮后，系统报错，提示如下：“Error.
An error occurred while processing your request.”

**Comment by zxc37880** [comment]
是否可請提供客戶名稱測試，謝謝。

**Comment by winder1986** [comment]
客户名称：华康测试

直接在正式站测试即可。

**Comment by zxc37880** [comment]
正式站已修改此BUG，麻煩再試一下，謝謝。

**Comment by winder1986** [comment]
好像还是不可以哦，麻烦再核实下

**Comment by zxc37880** [comment]
不好意思請在試一次，應該可以了。

**Comment by winder1986** [comment]
ok，已测试，感谢！
