### ISSUE TITLE
业务人员账号，所有客户列表应该可以查看所有人创建的已成交客户

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#77]
业务人员账号，所有人创建的已成交客户信息目前只能在已成交客户列表中查询，希望也可以在所有客户列表中查到。这样再查询客户的时候就不必再查询2个列表，只查询所有客户列表即可。

**Comment by zxc37880** [comment]
以佈上測試站，請測試。

**Comment by winder1986** [comment]
有些问题，在所有客户列表搜索客户，不能正确显示搜索内容。  测试账号：steven_li@dynacw.com，密码：123333，测试客户名称：纳爱斯集团有限公司
