### ISSUE TITLE
正式站，关键词功能失效

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#78]
正式站，关键词功能失效了，请核实。

测试客户名称：华康测试已成交2  （已设置“测试已成交”为关键词，所以“华康测试已成交2”不应该可以被创建）

**Comment by zxc37880** [comment]
目前是只有經銷商會有此功能，admin與業務是開放的，可以使用經銷商帳號測試一下。
如果是要把全部人都套用此規則在告知我再修改，謝謝。

**Comment by winder1986** [comment]
ok,没有问题了
