### ISSUE TITLE
无法删除客户，删除提示成功后，还可以查到。

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#80]
客户名称：“山东百事通国际旅行社有限公司(天津百事通国际旅行社有限公司、江西百事通国际旅行社有限公司、四川百事通国际旅行社有限公司、贵州百事通旅行社有限公司、江苏百事通国际旅行社有限公司、湖北海旅百事通国际旅行社有限公司、湖南百事通国际旅行社有限公司、重庆海外旅业(旅行社)集团有限公司、河南百事通旅游有限公司、无锡百事通旅行社有限公司)”

使用admin账号删除该客户，提示删除成功后，还可以查到。**请协助删除，感谢！**

**Comment by winder1986** [comment]
ID：1838

**Comment by zxc37880** [comment]
已刪除。
原因：未考慮客戶名稱長度超過100字，因此無法正確刪除，若之後要修正可重新部版至線上。

**Comment by winder1986** [comment]
好的，感谢！
