### ISSUE TITLE
admin无法删除客户信息，请协助删除

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#81]
客户名称：西安曲江出版传媒股份有限公司         ID：28450       无法删除（删除提示成功，但是查询仍显示），请协助删除，感谢！

**Comment by zxc37880** [comment]
![image](https://user-images.githubusercontent.com/14266495/62988677-c1018a00-be77-11e9-9390-9fc0faf1fbef.png)

已刪除，原因:資料庫內的客戶名稱前面多了一個空白符號，刪除時比對會剃除空白，因此刪除不到。
