### ISSUE TITLE
只能看到自己创建的过期客户（应该可以看到所有人创建的过期客户）

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#83]
业务账号和经销商账号只能看到自己创建的过期客户，应该可以看到所有人创建的过期客户
（2020.12.31日业务提出的问题：客户A已成交已过期，且客户A为侵权有效期，该类客户不显示在过期客户列表）

**Comment by winder1986** [comment]
经销商账号和业务账号，过期客户列表，只显示侵权和潜在过期客户，不显示已成交过期客户

**Comment by MartinWeng2020** [comment]
已修正
1.业务账号可以在过期客户看到所有人创建的过期客户
2.经销商账号可以在过期客户看到所有人创建的过期客户
3.经销商账号和业务账号在过期客户列表只显示侵权和潜在过期客户

**Comment by winder1986** [comment]
admin账号，“侵权客户列表”和“潜在客户列表”无法查看所有的侵权或潜在数据

**Comment by winder1986** [comment]
已修正在测试站了吗？现在测试站还未修正。

**Comment by MartinWeng2020** [comment]
此部分剛剛已修正在测试站了
1.业务账号可以在过期客户看到所有人创建的过期客户
2.经销商账号可以在过期客户看到所有人创建的过期客户
3.经销商账号和业务账号在过期客户列表只显示侵权和潜在过期客户

**Comment by winder1986** [comment]
部分账号（业务和经销商账号）看到的数据不一致。比如：车舜账号，过期客户列表数据130条；李永生账号，过期客户列表数据22869条；陈帅账号，过期客户列表数据2311条。

**Comment by MartinWeng2020** [comment]
部分账号（业务和经销商账号）看到的数据不一致 --已修正

**Comment by winder1986** [comment]
显示5383页，但是后面的没有数据，麻烦核实下

**Comment by MartinWeng2020** [comment]
显示5383页，但是后面的没有数据，麻烦核实下 --  已修正 (原本5383页，包含已成交资料，移除后已正常)

**Comment by winder1986** [comment]
已修正
