### ISSUE TITLE
经销商账号无法查看侵权证据

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#84]
经销商账号，已过期客户列表，查看详情，无法查看侵权证据

**Comment by MartinWeng2020** [comment]
无法查看侵权证据 是因为测试环境 当初建置客户时，并没有上传侵权证据，像是ID:5 ，北京绩优堂教育科技有限公司的资料有侵权证据

**Comment by winder1986** [comment]
点击查看“侵权证据”会报错：“404 - 找不到文件或目录。”，比如侵权客户：“华康测试”

**Comment by MartinWeng2020** [comment]
已修正，请重新新增客户，并上传侵权证据

**Comment by winder1986** [comment]
新增的侵权客户（调整为已过期后）可以查看侵权证据，但是原有的已过期侵权客户无法查看，报错404.例如：用友网络科技股份有限公司

**Comment by MartinWeng2020** [comment]
测试站因之前异动，没有留存到2020年所上传的侵权证据档案。正式站正常不会有这种情况，测试站可以测试2019之前上传的侵权证据档案，如客户名称 ： 江西卫视《美人帮》

**Comment by winder1986** [comment]
ok，了解了

**Comment by MartinWeng2020** [comment]
谢谢 辛苦了
