### ISSUE TITLE
创建客户逻辑错误

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#88]
正确逻辑应如下：
1：已成交客户过期3个月后可以被所有账号再次创建
2：侵权或潜在客户过期后可以被其他账号创建（不包含原经销商账号），过期1年后可以被所有账号创建（包含原经销商账号）

**Comment by winder1986** [comment]
正式站测试客户：华康测试   经销商A账号：107201803@qq.com，密码：Taipei2020   已成交已过期3个月（应可以再次创建），经销商B账号：Njlshkzt@sina.com，密码：Taipei2020  潜在过期未1年（不应再次创建）。但是测试结果正好相反，A不能登记提示“未满1年”，B可以创建

**Comment by MartinWeng2020** [comment]
您好，请问能否在测试站，重现类似这样的状况?  并请提供客户资讯，谢谢

**Comment by winder1986** [comment]
现在测试站的逻辑是正确的，但是正式站的是错误的，所以不需要调整测试站了，直接更新至正式站即可。以上，感谢!

**Comment by MartinWeng2020** [comment]
了解，谢谢，辛苦了~
