### ISSUE TITLE
新增客户--检查客户名称，弹出框内容无法显示

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#91]
1：已成交，已过期客户无法显示“历史成交时间，截止时间，购买字体”数据。测试客户：华康测试。
2：将“重要进度”描述更改为“购买字体”

**Comment by MartinWeng2020** [comment]
#91已修正

之前的#88 bug(如下)能否在测试站 再测试一次看看，怕这次修正会影响到

正式站测试客户：华康测试 经销商A账号：107201803@qq.com，密码：Taipei2020 已成交已过期3个月（应可以再次创建），经销商B账号：Njlshkzt@sina.com，密码：Taipei2020 潜在过期未1年（不应再次创建）。但是测试结果正好相反，A不能登记提示“未满1年”，B可以创建

**Comment by winder1986** [comment]
**有影响到#88**。测试站，测试客户：华康测试，帐号：hk.tangxin@foxmail.com密码：zjtd1602（可以创建，已成交已过期3月）；帐号：wang@myfont.com.cn密码:45688wh（不可以创建，侵权过期未满1年）

**Comment by MartinWeng2020** [comment]
#91 和 #88   皆已修正 再麻烦测试

**Comment by winder1986** [comment]
测试均已OK，感谢！
