### ISSUE TITLE
部分客户无法查看详情，报错。

### ISSUE THREAD

**Issue by winder1986** [chanchengliang/Dynacw_ChinaAgent#93]
部分客户无法查看详情，报错如下：Error.An error occurred while processing your request.
正式站，客户名称：广州市交互式信息网络有限公司 ID:13963             智威汤逊-中乔广告有限公司上海分公司 ID:120899

**Comment by MartinWeng2020** [comment]
已修正

**Comment by winder1986** [comment]
ok感谢！

**Comment by winder1986** [comment]
这几个客户，修改后保存时，报错：Error.An error occurred while processing your request.
URL:
http://chinaagent.dfo.dynacw.com.cn/CustomersEx/Details/13963
http://chinaagent.dfo.dynacw.com.cn/CustomersEx/Details/120899
http://chinaagent.dfo.dynacw.com.cn/CustomersEx/Details/94841

**Comment by MartinWeng2020** [comment]
已修正

**Comment by MartinWeng2020** [comment]
已修正，这几个客户会有问题是因为这些客户当初建立时没有建立登记时间

**Comment by winder1986** [comment]
奇怪，登记时间都是系统自动填写的，不需要手动填写

**Comment by MartinWeng2020** [comment]
此問題已修正

**Comment by winder1986** [comment]
OK,感谢！
